### PR TITLE
Fix parenthesis error and remove unused column name

### PR DESCRIPTION
**Pull request by kalenluciano**
This PR is to address some changes made by issue #96. I removed a parenthesis that was causing an error and an unused column name.

### CODE REVIEW

**Comment by mbodeantor** [comment]
@kalenluciano Weird, I swear I made that parenthesis fix somewhere. That state_name column is to enable search on the full state name instead of just a two letter abbreviation

**Comment by kalenluciano** [comment]
When I pulled down the main branch, it gave me an error when I ran `python app.py` but maybe I needed to pull again if it works for you locally.

As for the state_name, the one I removed is for labelling the returned values that we select in the sql query 
`SELECT
                data_sources.airtable_uid,
                data_sources.name AS data_source_name,
                data_sources.description,
                data_sources.record_type,
                data_sources.source_url,
                data_sources.record_format,
                data_sources.coverage_start,
                data_sources.coverage_end,
                data_sources.agency_supplied,
                agencies.name AS agency_name,
                agencies.municipality,
                agencies.state_iso`

It's only going to return these 12 values, which match with these column names: 1column_names = ['airtable_uid', 'data_source_name', 'description', 'record_type', 'source_url', 'record_format', 'coverage_start', 'coverage_end', 'agency_supplied', 'agency_name', 'municipality', 'state_iso']`. Adding the state_name to this column won't do anything, but I think it's probably best practice to remove the excess label. We still will check for matches in the state_name because you added this to the where clause of our sql query: state_names.state_name ILIKE %s

**Comment by mbodeantor** [comment]
No totally, just thought I had addressed it already.

Ah yeah I see now.

**Review by mbodeantor — APPROVED** [review]

**Review by josh-chamberlain — APPROVED** [review]

**Comment by josh-chamberlain** [comment]
hey nice catch

**Pull request merged**
