### PR TITLE
Dev → Main March 2024

### PR DESCRIPTION
**Pull request by josh-chamberlain**
Testing user login, maybe other things.

### Fixes

- https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/24

### Contains PRs

- https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/196

### Docs

- still need to make docs for this; API docs should be set

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
Testing login at https://data-sources.pdap.dev/login and the forms just refresh. Could be an envar issue, based on the `undefined/user` in the route? @mbodeantor 

Screen Shot 2024-03-12 at 1 45 55 PM

**Comment by josh-chamberlain** [comment]
@joshuagraber based on the above, I'm thinking we should have a catch-all error value for unpredictable issues, like:

> Something went wrong on our end. If you keep seeing this message, please email contact@pdap.io for assistance.

**Comment by mbodeantor** [comment]
@josh-chamberlain just updated the env vars

**Comment by joshuagraber** [comment]
> based on the above, I'm thinking we should have a catch-all error value for unpredictable issues, like:

Sounds good @josh-chamberlain I'll add an issue to add an error boundary component to render in case of any unexplained/uncaught API errors like this.

**Comment by josh-chamberlain** [comment]
Thanks @joshuagraber and @mbodeantor. I noticed just a couple more things:

- When the passwords don't match, we get a "Please provide your password" error which should probably read "Passwords must match". (image below)

- My password reset email took maybe 10 minutes, but by the time it showed up, the link took me to an expired token page. (image below). Can we extend that reset token to maybe 15–20 minutes, and add a line to the email about how long it'll take to expire?

- On the token expired page, instead of columns, can we just have the line of text with a `Request another password reset` button below it?

Screen Shot 2024-03-12 at 4 22 18 PM

Screen Shot 2024-03-12 at 4 36 23 PM

**Comment by joshuagraber** [comment]
Hey @josh-chamberlain, no probs.

A couple thoughts/questions:
> When the passwords don't match, we get a "Please provide your password" error which should probably read "Passwords must match". (image below)

The error in your screenshot is the password field validation (does PW meet all the required conditions), not the password mismatch error (see screenshot below). But the password match validation should happen first, so I'm a bit confused as to how you got to this state. Do you have more detailed steps to reproduce? 

Screenshot 2024-03-13 at 6 01 09 AM

(Another thing: I just noticed the form inputs clear on the password mismatch error, but that's a `design-system` problem. Will create an issue to preserve form input values after `onSubmit` validation errors in parent components.)

> My password reset email took maybe 10 minutes, but by the time it showed up, the link took me to an expired token page. (image below). Can we extend that reset token to maybe 15–20 minutes, and add a line to the email about how long it'll take to expire?

Agreed. It would also be nicer UX if we have an endpoint to validate this token on page load, so the user doesn't have to fill out the form and submit to know that it's expired. @mbodeantor Do you think it makes sense to add an issue to tackle this later, as an enhancement to the reset pw experience?

> On the token expired page, instead of columns, can we just have the line of text with a Request another password reset button below it?

Done. 

I also started the error boundary component and catchall "not found" route from #210 yesterday, so added that stuff here as well.
PR is [here](https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/211), if you want to add any related API changes @mbodeantor.

**Review by mbodeantor — APPROVED** [review]

**Pull request merged**
