### PR TITLE
adding endpoint to support data sources map

### PR DESCRIPTION
**Pull request by mbodeantor**
Resolves: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/240
Docs: https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/482/api/endpoints/data-sources-database

### CODE REVIEW

**Comment by joshuagraber** [comment]
@mbodeantor This looks great, thank you. Confirmed via command line that the endpoint returns expected data. Could we also support this endpoint on `/search-tokens`, so that we can fetch this data without explicit client-side auth?

**Comment by mbodeantor** [comment]
@joshuagraber Yup! should be in there now

**Review by joshuagraber — APPROVED** [review]

**Review by joshuagraber — CHANGES_REQUESTED** [review]
Hey @mbodeantor looks like I'm getting data returned as an array here rather than an object, e.g.:

```
[
        "recU0N2RiHdzmOkqa",
        "ShotSpotter policies for Detroit",
        "recsCx4e70CrvOc2X",
        "Detroit Police Department",
        "MI",
        "Detroit",
        42.42585,
        -83.051216
    ],
```

**Comment by mbodeantor** [comment]
@joshuagraber oops, wrong query. Should be fixed now

**Review by joshuagraber — APPROVED** [review]
Nice, lgtm!

**Pull request merged**
