### PR TITLE
test on existing user

### PR DESCRIPTION
**Pull request by mbodeantor**

### CODE REVIEW

**Comment by maxachis** [comment]
@mbodeantor I'm a little confused as to what fix is and what the originating issue is here. Why change the 'email' value from 'test' to 'test2'?

**Comment by mbodeantor** [comment]
@maxachis Sorry yeah, "test" is not an email in the database so the test will fail. "test2" is actually an email in the database

**Comment by mbodeantor** [comment]
@maxachis It's unclear to me where to store the HuggingFace token, can you add that to the README?

**Review by maxachis — APPROVED** [review]

**Comment by maxachis** [comment]
> @maxachis It's unclear to me where to store the HuggingFace token, can you add that to the README?

@mbodeantor I'm not sure what you're referring to or how that relates to this PR 🤔, as I don't believe I did anything with reference to HuggingFace in my changes to the `data-sources-app` repository. I've done quite a few things in the [data identification repository](https://github.com/Police-Data-Accessibility-Project/data-source-identification) that would reference HuggingFace, but there as well I'd need reference to where specifically the problem lies.

**Comment by mbodeantor** [comment]
@maxachis sorry wrong PR

**Pull request merged**
