### PR TITLE
Dev -> Main

### PR DESCRIPTION
**Pull request by mbodeantor**
contains:

- #184 
- #188 
- automated backend tests and linting checks as part of the PR process
- regularly scheduled API endpoint testing

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
can you say more about what all is in this? i.e. which PRs are contained and if any things did _not_ have a PR into dev that we might want to know about

**Comment by mbodeantor** [comment]
@josh-chamberlain For my part, just automated backend tests and linting checks as part of the PR process and regularly scheduled API endpoint testing
@joshuagraber can you comment on the other parts?

**Comment by joshuagraber** [comment]
Sure, @mbodeantor  @josh-chamberlain I believe all that's going in for the client here is #184 and #188.
184 is the only one to have any actual effect on the UI, and 188 is just fixes for testing.

**Comment by joshuagraber** [comment]
Also, FYI @mbodeantor I added [an issue here to add client build/lint/test scripts to run in CI as well](https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/191), so let me know if you have a preferred strategy there (same action file or different, etc.).

**Comment by mbodeantor** [comment]
@joshuagraber Hmmm yeah I would say probably the same file, maybe just a separate step to make it clear where any fails occured?

**Pull request merged**
