### PR TITLE
refactor: search results and quick search

### PR DESCRIPTION
**Pull request by joshuagraber**
Will complete #185 when merged to `main`.

To test:
- Run the app.
- Ensure that the `QuickSearchForm` displays per updates described in #185.
- Search for data sources, ensure the search page displays per updates described in #185.

### CODE REVIEW

**Comment by mbodeantor** [comment]
@joshuagraber Seeing that weird routing behavior again leading to no results:
http://localhost:8888/search/calls/undefined/search-tokens?endpoint=quick-search&arg1=calls&arg2=chicago

**Comment by mbodeantor** [comment]
@joshuagraber I reverted my base url variable but the 5173 port is still hardcoded somewhere:

http://localhost:5173/search-tokens?endpoint=quick-search&arg1=calls&arg2=chicago

**Comment by mbodeantor** [comment]
@joshuagraber Not that I can see

**Comment by joshuagraber** [comment]
> Not that I can see

@mbodeantor I'm not sure what it might be, then. I've got nothing hardcoded to any localhost value locally, env var or otherwise.

**Comment by mbodeantor** [comment]
Weird, not sure where it was getting that but a clean virtual env seemed to fix it. I'm seeing the changes except for the quick search tip "For example, you could search for..."

**Comment by joshuagraber** [comment]
> Weird, not sure where it was getting that but a clean virtual env seemed to fix it.

Haha, when in doubt, clear the cache. 

> I'm seeing the changes except for the quick search tip "For example, you could search for..."

Oops, sorry, I should have mentioned: need to run `npm i` from `/client`, as we updated `design-system` with those changes. Mea culpa.

**Comment by mbodeantor** [comment]
Didn't seem to work for me

**Comment by joshuagraber** [comment]
Hmm, I've got it locally @mbodeantor. Does your `/client/package.json` on this branch have `"pdap-design-system": "^2.5.0",`?

Screenshot 2024-03-04 at 4 01 38 PM

**Comment by mbodeantor** [comment]
Yeah my package.json matches

**Comment by joshuagraber** [comment]
> Yeah my package.json matches

Weiiiiiird. Did you ever link the design system locally using `npm link` to test anything? If so, that symlink may still be active. If you run `npm ls -g --depth=0 --link=true` you should get all linked modules as output. If `pdap-design-system` is in the output, run `npm unlink pdap-design-system`, then (maybe) `rm -rf node_modules` then `npm ci`.

If that doesn't solve it, then I'm baffled 😅.

**Comment by joshuagraber** [comment]
> Nope, no symlinks.

@mbodeantor Then I really don't know what might be happening here, to be honest. Could try clearing npm cache? `npm cache clean` (might require `--force` flag)?

@josh-chamberlain Can you try verifying this, as a sanity check?

**Comment by mbodeantor** [comment]
Clearing the cache did it!

**Review by mbodeantor — APPROVED** [review]

**Pull request merged**
