### PR TITLE
Feature/api auth

### PR DESCRIPTION
**Pull request by kalenluciano**

### CODE REVIEW

**Comment by kalenluciano** [comment]
I'm running into a roadblock creating a protected route for quick search. I got the sign up and login function to work properly. The sign up successfully stores a hashed password in Supabase. The login function checks the input password with the hashed password and creates and sends an access token. I confirmed that all of this is working already.

However, when I add in @jwt_required() decorator, I got this error: 
`jwt.exceptions.InvalidSignatureError: Signature verification failed`

Based on my research, it looks like there's a chance that there might be a conflict between the different jwt libraries I tried when implementing the access token (the three relevant packages are flask_jwt_extended, pyJWT, and jwt. I tried uninstalling all the packages and resetting the virtual environment with just the flask_jwt_extended (which is the one I'm actually using now to create and verify a token). I still was getting the same error though.

Any recommendations for how to overcome this roadblock?

**Comment by mbodeantor** [comment]
@kalenluciano might be easier to do this on a call but where are you checking the token? I see the flow in User but don't see how that would tie to the quick-search endpoint. Haven't done this before, but I think defining a decorator like in here that checks the api token might be required: https://blog.teclado.com/api-key-authentication-with-flask/

**Comment by mbodeantor** [comment]
Awesome! Really cool to see it all working. The one thing I saw is I get an error when I didn't provide an API key instead of it failing gracefully with the "Please provide an API key" message.

**Comment by mbodeantor** [comment]
Also could you add a few notes on API usage? What is required for authorization, how to post it to the quick-search endpoint etc.

**Comment by mbodeantor** [comment]
Is the JWT still being used? Probably could be removed

**Comment by mbodeantor** [comment]
looks ```compare_digest(user_data.get('api_key'), api_key)``` won't work if user_data doesn't return a match from Supabase and is an empty dict as it is comparing a dict to a str

**Comment by mbodeantor** [comment]
(when passing an invalid api key)

**Comment by kalenluciano** [comment]
This should be fixed now. I added a check to make sure that there was an API key returned from Supabase before the compare_digest function. If there isn't, it returns false for is_valid(api_key). 

Fyi, the quick search function isn't working for this branch anymore though because we changed to querying for the new tables and this has the old code. I merged the query-new-table branch with this one locally and double checked that it does work with the updated code

**Comment by mbodeantor** [comment]
@kalenluciano Sorry found one more way to break it. The split will error if you forget the "Bearer" and just pass the api key.

**Comment by kalenluciano** [comment]
This should be fixed now!

**Review by mbodeantor — APPROVED** [review]
Excellent!

**Pull request merged**
