### PR TITLE
dev → main 3/25/24

### PR DESCRIPTION
**Pull request by josh-chamberlain**
Contains 

- https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/211
- https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/215
- https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/220
- https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/228
- https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/235
- #223 
- #237 
- #235 
- #221

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
@mbodeantor how do you feel about merging into main for most things, and keeping dev up to date / using it to test large or critical things that need to be deployed to test properly → merged into main individually?

**Comment by mbodeantor** [comment]
@josh-chamberlain That could work, it would then be incumbent on anyone merging their code into dev to first merge main into dev.

**Comment by joshuagraber** [comment]
PR is [here](https://github.com/Police-Data-Accessibility-Project/data-sources-app/pull/235) for the password hints on `/reset-password/:token`

**Comment by mbodeantor** [comment]
@joshuagraber @josh-chamberlain I think this is ready to go then?

**Comment by mbodeantor** [comment]
Actually it doesn't look like dev built successfully in DigitalOcean. @maxachis Can you look into modifying the run command in DO as needed for the new structure in app.py?

**Comment by maxachis** [comment]
> @josh-chamberlain That could work, it would then be incumbent on anyone merging their code into dev to first merge main into dev.

@josh-chamberlain @mbodeantor Alternatively, we create a Github Action which, on a Dev PR, merges Main into Dev first. I could create an issue on that. Would save time and reduce risk of someone forgetting to do that.

**Comment by josh-chamberlain** [comment]
I think this will happen on its own—when you create a PR, you can see how many commits you are behind main. We could maybe schedule a job to open a PR, but not merge it.

**Comment by mbodeantor** [comment]
@josh-chamberlain @maxachis I think the github action on PR could be handy. We already have some running on PR open so it would just be a fairly simple addition to the pull file

**Review by mbodeantor — APPROVED** [review]

**Pull request merged**
