### PR TITLE
refactor: data source static view

### PR DESCRIPTION
**Pull request by joshuagraber**
This will handle #150 when merged into `main`. Not marking as resolved as this PR goes to `dev`.

## To test
Run app locally, ensure that behavior and styling match requirements in #150. See screen recording below for successful demo.

https://github.com/Police-Data-Accessibility-Project/data-sources-app/assets/68428039/0562dd96-6187-4857-92e0-5cba706dc3a0

### CODE REVIEW

**Comment by mbodeantor** [comment]
Nice! Looks good. The only thing I see is some of the dates have a line for null as well as an actual date
Screen Shot 2024-01-08 at 11 30 10 AM

**Review by josh-chamberlain — APPROVED** [review]
looks good to me (aside from date changes mentioned by marty)

**Comment by joshuagraber** [comment]
Good catch @mbodeantor, thank you! This is updated and ready for re-review.

**Review by mbodeantor — APPROVED** [review]
Nice!

**Pull request merged**
